#!/bin/bash
set -e

POSTGRESQL_USER=${POSTGRESQL_USER:-"postgres"}
POSTGRESQL_PASS=${POSTGRESQL_PASS:-"postgres"}
POSTGRESQL_DB=${POSTGRESQL_DB:-"postgres"}

POSTGRESQL_BIN_PATH=/usr/local/pgsql/bin
POSTGRESQL_CONFIG_FILE=/usr/local/pgsql/data/postgresql.conf
POSTGRESQL_DATA=/data

if find $POSTGRESQL_DATA -maxdepth 0 -empty | read v; then
    mkdir -p $POSTGRESQL_DATA
    chown -R postgres:postgres $POSTGRESQL_DATA
    sudo -u postgres $POSTGRESQL_BIN_PATH/initdb -D $POSTGRESQL_DATA
    sudo -u postgres $POSTGRESQL_BIN_PATH/postgres --single --config-file=$POSTGRESQL_CONFIG_FILE <<< "CREATE USER $POSTGRESQL_USER WITH SUPERUSER;"
    sudo -u postgres $POSTGRESQL_BIN_PATH/postgres --single --config-file=$POSTGRESQL_CONFIG_FILE <<< "ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASS';"
    sudo -u postgres $POSTGRESQL_BIN_PATH/postgres --single --config-file=$POSTGRESQL_CONFIG_FILE <<< "CREATE DATABASE $POSTGRESQL_DB OWNER $POSTGRESQL_USER;"
fi

exec sudo -u postgres $POSTGRESQL_BIN_PATH/postgres --config-file=$POSTGRESQL_CONFIG_FILE
